import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Header from "./components/Header";
import Providers from "./context/Provider";
import { MessageProvider } from '@/app/context/MessageProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
});

export const metadata: Metadata = {
  title: "Near Stack",
  description: "Generated by create next app",
};

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
      <Providers>
        <Header />
        <main className="h-[92vh]">{children}</main>
      </Providers>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'h-full w-full'}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
